// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skvejcsqyebgkdknfmjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdmVqY3NxeWViZ2tka25mbWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTQ0MjQsImV4cCI6MjA3MDQ5MDQyNH0.wKxT55NLeOUVowg5MAr5RliIhaKHyyI01UQFVsAsElI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});